export const USER_LOGIN = 'USER_LOGIN';
export const USERS_ERROR = 'USERS_ERROR';
export const USERS_LOGOUT = 'USERS_LOGOUT';
export const USER_LOADING= 'USER_LOADING';


export const FETCH_CATG_LIST ='FETCH_CATG_LIST';
export const FETCH_CATG_REQ ='FETCH_CATG_REQ';
export const FETCH_CATG_ERROR ='FETCH_CATG_ERROR';


export const FETCH_PRODUCT_LIST ='FETCH_PRODUCT_LIST';
export const FETCH_PRODUCT_REQ ='FETCH_PRODUCT_REQ';
export const FETCH_PRODUCT_ERROR ='FETCH_PRODUCT_ERROR';



export const FETCH_CITY_LIST ='FETCH_CITY_LIST';
export const FETCH_CITY_REQ ='FETCH_CITY_REQ';
export const FETCH_CITY_ERROR ='FETCH_CITY_ERROR';